Proxy:
  ServerHost: "0.0.0.0"
  ServerPort: 5020
  AllowedIPs:
    - "192.168.1.10"
    - "192.168.2.0/24"
  MaxConnections: 50

ModbusServer:
  ModbusServerHost: "192.168.1.100"
  ModbusServerPort: 502
  ConnectionTimeout: 10
  DelayAfterConnection: 0.5
  MaxRetries: 5
  MaxBackoff: 30.0

Logging:
  Enable: true
  LogFile: "modbus_proxy.log"
  LogLevel: "INFO"
