version: 0.0.3
Proxy:
  ServerHost: 0.0.0.0
  ServerPort: 5020
ModbusServer:
  ModbusServerHost: 192.168.178.196
  ModbusServerPort: 5020
  ConnectionTimeout: 10
  DelayAfterConnection: 0.5
Logging:
  Enable: true
  LogFile: /var/log/modbus_proxy.log
  LogLevel: INFO
